name: Greenish Orange
favicon: null
layout_spectrum: 0.2459
typography_spectrum: 0.34737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-91230-9
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#ffffff'
    - '#b9b9b9'
    - '#828282'
    - '#606060'
  brandStrength: 0.5
  lightness: 0.11509294551797211
  saturation: 0.39781206916086376
  rhythmicContrast: 0.16231667017564178
purpose: []
