name: Greenish Orange
favicon: null
layout_spectrum: 0.52836
typography_spectrum: 0.5995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-91230-9
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#9b9893'
    - '#905833'
    - '#332620'
    - '#cfd1ce'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
