typography_spectrum: 0.68291
color:
  brandColors:
    - '#fefefe'
    - '#9b9893'
    - '#905833'
    - '#332620'
    - '#cfd1ce'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-91230-9
  facebook: null
  twitter: null
name: Greenish Orange
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Web Design & Development
purpose: []
