name: Greenish Orange
favicon: null
layout_spectrum: 0.2459
typography_spectrum: 0.34737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-91230-9
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#370e16'
    - '#a68a7f'
    - '#6e4237'
    - '#a5cbcc'
    - '#c14f4e'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
